# Generated by Django 4.2.2 on 2023-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
